version: '3'

podotegreen:
  build:
    context: .
    dockerfile: Dockerfile.prod
  ports:
    - '3001:3001'
  container_name: podotegreen
  logging:
    driver: awslogs
    options:
      awslogs-region: ap-northeast-2
      awslogs-group: /aws/ec2/podote-server
      awslogs-stream: apilogs
      awslogs-datetime-format: \%Y-%m-%d %H:%M:%S\]
      tag: '{{.Name}}-{{.ID}}'
  restart: unless-stopped
